### ISSUE TITLE
summary view shows empty key but expanded view does not

### ISSUE THREAD

**Issue by tromey** [devtools-html/devtools-core#688] opened 2017-09-18 14:35 UTC
To reproduce, open the console and enter
```
q = { "": 57, a:9, b:3}
```

The summary view is ok:
![image](https://user-images.githubusercontent.com/1557670/30547354-48435f20-9c4c-11e7-9a4d-2b4f7a31e0da.png)

The expanded view is missing the empty key:
![image](https://user-images.githubusercontent.com/1557670/30547390-5fd1b3da-9c4c-11e7-8e0a-c702012683cb.png)

**Comment by Loirooriol** [comment] 2017-09-18 21:26
And also for strings containing only whitespace. Since I fixed the same issue for VariablesView, I checked the new Object Inspector and it worked properly some weeks ago. So it must be a recent regression.

**Comment by nchevobbe** [comment] 2018-04-26 12:27
looks fixed in Nightly :)

**Closed by nchevobbe** 2018-04-26 12:27 UTC
Labels: devtools-reps
