### ISSUE TITLE
HTML entities are replaced by their original value

### ISSUE THREAD

**Issue by wagnerand** [devtools-html/devtools-core#825] opened 2017-12-01 13:25 UTC
This looks quite scary:
![screen shot 2017-12-01 at 14 13 33](https://user-images.githubusercontent.com/873258/33484598-46d33c8c-d6a3-11e7-917e-ed40ca0f7d1e.png)

However, when you go into edit mode, it turns out that the second quote is actually the just the HTML entity.
![screen shot 2017-12-01 at 14 13 24](https://user-images.githubusercontent.com/873258/33484602-49cde388-d6a3-11e7-9834-498290c2cb38.png)

**Comment by nchevobbe** [comment] 2017-12-01 13:39
Hello @wagnerand , could you gives us some steps to reproduce what you are seeing ?
It's not clear to me what you did, and how this should look.

By the way, this repo is only for some shared npm-packages used by the devtools; your bug would be better filed (and tracked) on Bugzilla. But before moving it there, let's have a proper steps to reproduce, and check if there aren't already a bug about this.

**Comment by wagnerand** [comment] 2017-12-01 13:45
Hi!

STR:

1. Install the theme from https://addons-dev.allizom.org/en-US/firefox/addon/quantum-one/
2. In Firefox, go to "about:addons", select the "Themes" tab.
3. Run the page inspector and select the description of the theme you just installed.

Thanks, I will file bugs on bugzilla in the future. I was referred to here by @codehag :)

**Comment by wagnerand** [comment] 2017-12-01 13:46
What it should look like is `value="&quot;` instead of `value=""` in non-edit mode.

**Comment by nchevobbe** [comment] 2017-12-01 13:56
@wagnerand is this a simpler STR ?

**Steps to reproduce:**
1. Go to `data:text/html,<div data-attribute="&quot;oops&quot;">attribute with htmlentity</div>`
2. Inspect the "Attribute with htmlentitiy" element

**Expected results:**

data-attribute should be `data-attribute="&quot;oops&quot;">`

**Actual results:**

data-attribute id displayed as `data-attribute=""oops"">`, making the attribute looks odd

**Comment by wagnerand** [comment] 2017-12-01 13:59
@nchevobbe I believe your example is related, but it does different things:
* It replaces single qoutes by double quotes
* It does not show the actual code neither in edit-mode nor in non-edit-mode.

**Comment by nchevobbe** [comment] 2017-12-01 14:04
could you try to have a similar bug to the one from your first comment using a data-uri ? it would be simpler than having to install an addon :) Also, i'd like to see if it's not a xul-related bug

**Comment by wagnerand** [comment] 2017-12-01 14:07
`data:text/html,<div data-attribute="&quot; onclick=&quot;">attribute with htmlentity</div>` is similar to the original bug, but I can't reproduce the exact same behavior. Might be XUL vs HTML thing...

**Comment by wagnerand** [comment] 2017-12-01 14:11
Ok, try `data:text/html,<div data-attribute="&quot; onclick=&quot;javascript:alert('1');">attribute with htmlentity</div>`.

**Comment by nchevobbe** [comment] 2017-12-01 15:07
Okay, this looks like https://bugzilla.mozilla.org/show_bug.cgi?id=967493 , so I'm closing this here, and you can follow the bug on Bugzilla :)

**Closed by nchevobbe** 2017-12-01 15:07 UTC

**Comment by wagnerand** [comment] 2017-12-01 15:14
Thank you!
