### ISSUE TITLE
Running launchpad with `yarn start` is broken

### ISSUE THREAD

**Issue by bomsy** [devtools-html/devtools-core#410] opened 2017-06-05 16:27 UTC
The launchpad throws an error! 
`Uncaught TypeError: Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined`.

Looks like its related to the  chrome-remote-interface module.
![screen shot 2017-06-05 at 5 07 46 pm](https://cloud.githubusercontent.com/assets/792924/26792926/f700fe54-4a13-11e7-93dd-85d69c0f555f.png)

#### STR
* do `cd packages/devtools-launchpad`
* run `yarn start`

**Comment by jasonLaster** [comment] 2017-06-09 17:09
Filed this issue: https://github.com/cyrus-and/chrome-remote-interface/issues/162
The workaround is to comment out `CDP = require("chrome-remote-interface")`

**Comment by jasonLaster** [comment] 2017-06-12 20:15
I've tried a bunch of things and am still getting stuck. 

Here's a project that works: https://github.com/jasonLaster/cri-testcase
all it does is install webpack w/ CRI

I've tried reverting CRI to an earlier version and that doesn't work either.

The issue is that the webpack context `this` is undefined and thus is creating a situation where undefined does not have the TYPED_ARRAY property

**Comment by jasonLaster** [comment] 2017-06-14 11:51
landed #451 as a quick fix

**Comment by cyrus-and** [comment] 2017-06-14 13:06
After a painful bisection process is seems that the breaking change happened in d8a754f6f12744db3e0c3ea3bd9a8152856a3cec (i.e., fda7b84593ca6b1e9ce44d9eb9e1d031b7fcc394 is the last working commit). Can you confirm that?

**Comment by cyrus-and** [comment] 2017-06-14 13:15
In particular [this] looks like to be the culprit here:

```diff
         excluded = excluded || !!request.match(webpackConfig.babelExcludes);
       }

-      return excluded && !request.match(/node_modules(\/|\\)devtools-/)
+      return excluded && !request.match(/devtools-/);
     },
     loaders: [
```

Reverting this line avoids that error.

[this]: https://github.com/devtools-html/devtools-core/commit/d8a754f6f12744db3e0c3ea3bd9a8152856a3cec#diff-e85cc8bdcc8288e774b1581ccd4285ceR38

**Comment by bomsy** [comment] 2017-06-14 21:27
thanks @cyrus-and, that fixes it.

**Closed** 2017-06-15 12:15 UTC
Labels: bug, LaunchPad

**Comment by jasonLaster** [comment] 2017-06-18 03:44
Thanks @cyrus-and!

What was the issue?

**Comment by cyrus-and** [comment] 2017-06-18 21:29
@jasonLaster I've simply applied the bisection and that line looked suspicious, I didn't dig into the issue but I think the problem was that the `node_modules` folder wasn't properly ignored.
