### ISSUE TITLE
[Luanchpad] Hot Reloading

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#217] opened 2017-02-27 22:47 UTC
We should show something next to hot reloading to indicate it's broken. 
Also disable the button

**Comment by nchevobbe** [comment] 2017-02-28 12:54
Agree, I spent 15 minutes wondering what mistake I did to find out it was due to hot reloading being broken :)

**Comment by wldcordeiro** [comment] 2017-02-28 16:43
This is kind of a dupe of #195? I found info on how to fix it but just hadn't chased that yet. You're welcome to try @nchevobbe

**Closed** 2017-03-04 02:39 UTC
